export const students = [
  {
    id: 1,
    name: "Nguyen An",
    email: "an.nguyen@gmail.com",
    age: 19,
    avatar: "/images/concho.jpg",
  },
  {
    id: 2,
    name: "Tran Binh",
    email: "binh.tran@fpt.edu.vn",
    age: 22,
    avatar: "",
  },
  {
    id: 3,
    name: "Le Chi",
    email: "chi.le@fpt.edu.vn",
    age: 26,
    avatar: "",
  },
  {
    id: 4,
    name: "Pham Duong",
    email: "duong.pham@gmail.com",
    age: 20,
    avatar: "/images/concho.jpg",
  },
  {
    id: 5,
    name: "Vo Em",
    email: "em.vo@fpt.edu.vn",
    age: 24,
    avatar: "/images/concho.jpg",
  },
  {
    id: 6,
    name: "Hoang Giang",
    email: "giang.hoang@gmail.com",
    age: 27,
    avatar: "/images/concho.jpg",
  },
  {
    id: 7,
    name: "Bui Hai",
    email: "hai.bui@fpt.edu.vn",
    age: 21,
    avatar: "/images/concho.jpg",
  },
  {
    id: 8,
    name: "Dang Khoa",
    email: "khoa.dang@gmail.com",
    age: 23,
    avatar: "",
  },
  {
    id: 9,
    name: "Nguyen Linh",
    email: "linh.nguyen@fpt.edu.vn",
    age: 18,
    avatar: "",
  },
  {
    id: 10,
    name: "Tran Minh",
    email: "minh.tran@gmail.com",
    age: 25,
    avatar: "",
  },
];
